### ISSUE TITLE
Add Hackerrank problem URL in each solution

### ISSUE THREAD

**Issue by arsho** [arsho/Hackerrank_Python_Domain_Solutions#7]
Currently each solution file has multi line commend in top.
Add a new line that will show problem URL in each of the solution file.

**Current scenario:**

```
'''
Title     : Finding the percentage
Subdomain : Data Types
Domain    : Python
Author    : Ahmedur Rahman Shovon
Created   : 15 July 2016
'''
```
**Success criteria:**

```
'''
Title     : Finding the percentage
Subdomain : Data Types
Domain    : Python
Author    : Ahmedur Rahman Shovon
Created   : 15 July 2016
Problem   : https://www.hackerrank.com/challenges/finding-the-percentage/problem
'''
```

**Comment by allEyezOnCode** [comment]
I can work on it but how do you want to do ?  I thought about some solutions but i want to be sure there isn't any easier solution

**Comment by arsho** [comment]
@allEyezOnCode, sounds great that you can work on it. 
FYKI, I have updated the issue description. 
No, I do not think there is an easier solution.

**Comment by arsho** [comment]
@allEyezOnCode , I will prefer if a script can update existing header of each section to include the problem URL.
Remember each of the solution files has five information already: _title_, _domain_, _subdomain_, _author_ and _created_. The script should be able to append the sixth information _problem url_ without replacing the existing information.

**Comment by arsho** [comment]
This issue is resolved by @allEyezOnCode.
Merged pull request: https://github.com/arsho/Hackerrank_Python_Domain_Solutions/pull/8
